### ISSUE TITLE
Get Current Chromium Browser Tab

### ISSUE THREAD

**Issue by sly-fox-git** [alfredapp/update-automation-tasks-workflow#1]
Please add Title|URL option

**Comment by vitorgalvao** [comment]
The reason it’s `URL|Title` is that titles often contain `|` and valid URLs can’t. That allows you to then reliably split the lines in two. The reverse wouldn’t allow it. Could you elaborate on what’s the next step you intend after a `Title|URL` output, so as to think of the best approach?

**Comment by sly-fox-git** [comment]
I currently use Keyboard Maestro to achieve this. For instanced when I need to paste the Title + URL in email or notes, I use "burl" keyword with the following settings in Keyboard Maestro

[%FrontBrowserTitle%](%FrontBrowserURL%)

The result looks like this:

Get Current Chromium Browser Tab · Issue #1 · alfredapp/update-automation-tasks-workflow - https://github.com/alfredapp/update-automation-tasks-workflow/issues/1

I also have Markdown URL keyword that produces this

[Get Current Chromium Browser Tab · Issue #1 · alfredapp/update-automation-tasks-workflow](https://github.com/alfredapp/update-automation-tasks-workflow/issues/1)

It would be great to see the ability to set custom URL settings in Alfred.

**Comment by vitorgalvao** [comment]
> The result looks like this:
> 
> Get Current Chromium Browser Tab · Issue #1 · alfredapp/update-automation-tasks-workflow - #1

That is the `Title` option.

> I also have Markdown URL keyword that produces this
> 
> [Get Current Chromium Browser Tab · Issue #1 · alfredapp/update-automation-tasks-workflow](https://github.com/alfredapp/update-automation-tasks-workflow/issues/1)

That is `URL|Title` connected to a [Split Arguments](https://www.alfredapp.com/help/workflows/utilities/split-arg/):

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1699443/176972513-e51873a9-1e3a-4011-a0af-8c5ab72835f9.png">

Which then you use where you want as `[{var:split2}]({var:split1})`. Though it could maybe be more convenient (see below), as they may occasionally split a title too.

> It would be great to see the ability to set custom URL settings in Alfred.

Making it allow a custom configuration would start to veer into too much complexity. I’m thinking of adding `URL<tab>Title` and `Title<tab>URL` options. Any reason those wouldn’t work for your use cases?

**Comment by vitorgalvao** [comment]
Pushing a change to replace the `|` option with the two `<tab>` options. I’d like to get it out sooner rather than later to avoid breaking as much as possible.

Thank you for your request. In the future, please make them [in the forum](https://www.alfredforum.com) or [alfredapp/automation-tasks](https://github.com/alfredapp/automation-tasks). The latter is the correct repo, since this one is for the Workflow which will soon no longer be needed.
